version: '3'
services:
  database:
    image: postgres:12-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: secret